---
title: "Lab 2 - Data wrangling"
author: "Prabhjot Singh"
date: "12 Feb, 2026"
format: 
  html: default # for speed
  pdf: default # for final output

---


```{r}
#| eval: true
#| message: false

library(tidyverse)
```

```{r}
midwest
```

# Questions

## Part 1

### Question 1
```{r}
#| eval: true
#| message: false

midwest|>count(state)|>arrange(desc(n))
```
#### Illinois has the highest number of counties (102), and Wisconsin has lowest number of counties (72)

\newpage

### Question 2
```{r}
midwest |>
  count(county, state) |>
  count(county, name = "freq") |>
  filter(freq >= 2)
```
\newpage

### Question 3
```{r}
midwest |>filter(popdensity > 25000) |>select(county, state, popdensity, poptotal, area)|>arrange(desc(popdensity))

```
```{r}
midwest |>
  filter(popdensity == max(popdensity)) |>
  select(county, state, popdensity, poptotal, area)


```

\newpage

### Question 5

\newpage

### Question 6

\newpage

### Question 7

\newpage

### Question 8

\newpage

## Part 2


### Question 9

